### ISSUE TITLE
Call For Proposal Poster

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#10]
### Acceptance Criteria
- [x] CFP poster

### Due Date
TBD

### Output
Poster file

**Comment by assyafii** [comment]
waiting for content done, now preparing the template

**Comment by assyafii** [comment]
Done, need review in https://drive.google.com/drive/u/1/folders/1eBfC-D1kioXECg38KiTRnHaBJ7A_M8Pv
