### ISSUE TITLE
Sponsorship Prospectus Document

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#11]
Acceptance Criteria
- [x] Sponsorship Prospectus document based on the content without Virtual Event Venue

**Comment by assyafii** [comment]
Ongoing progress, https://docs.google.com/presentation/d/1Jv9nHRwtH03MKPcg0120Vas7HC6xKxeeVs0Wo-BesXg/edit#slide=id.p

**Comment by whippedcreamm** [comment]
Hi kak @assyafii & @zufardhiyaulhaq i have added some content needed based on sponsorship documents draft here https://docs.google.com/presentation/d/1Jv9nHRwtH03MKPcg0120Vas7HC6xKxeeVs0Wo-BesXg/edit?usp=sharing feel free to change or replace anything. Thanks!
