### ISSUE TITLE
Ensure all organizer take LFC102 course

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#13]
Organizer:
- [x] Zufar Dhiyaulhaq
- [x] Irwan Shofwan
- [x] Sartika Lestari
- [x] Bachril Qirom
- [x] Giri Kuncoro
- [x] Muhammad Luthfi As Syafii
- [x] Gofrendi Gunawan
- [x] Dewa Putu Prasta Maha Gangga
- [x] Aris C. Risdianto

**Comment by zufardhiyaulhaq** [comment]
@cloudnative-id/kubernetes-community-days folks, please take LFC102 by end of this week so we can continue to progress. https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/

**Comment by prastamaha** [comment]
I have completed the course, here is the evidence [link](https://www.credly.com/badges/40f246a7-a289-403f-8b7f-a62612c032e4/public_url)

**Comment by zufardhiyaulhaq** [comment]
this is a hard requirement for us to have access to SurveyMonkey and Bevy. please provide the badge link once you take the course @cloudnative-id/kubernetes-community-days 

https://github.com/cncf/kubernetes-community-days/issues/402

**Comment by ariscahyadi** [comment]
I have done it. Please check it [here](https://www.credly.com/badges/696f01e2-a03e-4474-9a27-b42e1380ad5e/).

**Comment by zufardhiyaulhaq** [comment]
I have done it, please check it [here](https://www.credly.com/users/zufardhiyaulhaq/badges).

**Comment by assyafii** [comment]
I have done it, please check it [here](https://www.credly.com/users/assyafii/badges)

**Comment by girikuncoro** [comment]
Done https://www.credly.com/badges/368feb5a-ed4f-469d-a5ca-1965936e2bac/public_url

**Comment by goFrendiAsgard** [comment]
Certificate: https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/3dbec326-cab6-4720-9504-d69343fa71fb-gofrendi-gunawan-inclusive-open-source-community-orientation-lfc102-certificate.pdf

Sorry, not sure how I can access the badge URL :(

**Comment by zufardhiyaulhaq** [comment]
no worries mas @goFrendiAsgard, thanks

**Comment by bachrilq** [comment]
Done please check it [here](https://www.credly.com/badges/d5891361-8d38-4cf4-9385-0910080adfa7/public_url)

**Comment by whippedcreamm** [comment]
Done https://www.credly.com/badges/6ca9ca49-5bf5-4229-8ac0-40838f8aea9c/public_url

**Comment by irwanshofwan** [comment]
Done https://www.credly.com/badges/623c6f4e-c569-4c82-b5c2-12ab5eb2066a

**Comment by zufardhiyaulhaq** [comment]
thanks @cloudnative-id/kubernetes-community-days awesome!
