### ISSUE TITLE
Community Partner Promotion

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#27]
Acceptance Criteria:

Ask other communities to become a partner of Kubernetes Community Days:
having community-operator bot:
- [x] IDDevOps @zufardhiyaulhaq
  - [x] contacted 
- [x] golang indonesia @zufardhiyaulhaq 
  - [x] contacted 
- [x] ruby Indonesia @zufardhiyaulhaq 
  - [x] contacted 
- [x] javascript Indonesia @zufardhiyaulhaq 
  - [x] contacted 
- [x] nodejs Indonesia @zufardhiyaulhaq 
  - [x] contacted 
- [x] opennetworking indonesia @zufardhiyaulhaq  
  - [x] contacted 
- [x] openstack Indonesia  @zufardhiyaulhaq 
  - [x] contacted 

other communities:
- [ ] python Indonesia @goFrendiAsgard 
  - [x] contacted 
- [ ] GCP Indonesia @girikuncoro 
  - [ ] contacted 
- [ ] AWS UG Indonesia @goFrendiAsgard 
  - [x] contacted 
- [ ] GDG Semarang @goFrendiAsgard 
  - [x] contacted
- [ ] Generation Girl Indonesia @zufardhiyaulhaq (skip)
  - [x] contacted 
- [x] SDx Indonesia @assyafii 
  - [x] contacted 
- [ ] LinuxSec
  - [ ] contacted
- [x] DeepTech @zufardhiyaulhaq 
  - [x] contacted
- [x] PHP Indonesia @zufardhiyaulhaq 
  - [x] contacted
- [x] OpenSUSE Indonesia @zufardhiyaulhaq 
  - [x] contacted
- [x] Kelompok Linux Arek Suroboyo @assyafii 
  - [x] contacted
- [x] Komunitas GNU/Linux Malang @assyafii 
  - [x] contacted
- [x] Girls Force Telkom University @assyafii 
  - [x] contacted   

University lab & club:
- [x] ProClub (Telkom University) @zufardhiyaulhaq 
  - [x] contacted 
- [x] Adaptive Network Lab (Telkom University) @assyafii 
  - [x] contacted 
- [ ] NEV (ITTP) @assyafii 
  - [x] contacted  
- [ ] Telecom Infra Project Community Lab (Tel-U) @assyafii 
  - [x] contacted  
- [x] BCC Filkom (Universitas Brawijaya) @irwanshofwan 
  - [x] contacted  
- [x] POROS Filkom (Universitas Brawijaya) @irwanshofwan 
  - [x] contacted

**Comment by zufardhiyaulhaq** [comment]
@assyafii any response from KLIM, KLAS, Girl Force, NEV, and Telecom Infra project? can you follow up?

**Comment by zufardhiyaulhaq** [comment]
@irwanshofwan any response from POROS? can you follow up?

**Comment by goFrendiAsgard** [comment]
I have send email to Python Id
As well as asking the organizers in AWS UG telegram group.

**Comment by assyafii** [comment]
> @assyafii any response from KLIM, KLAS, Girl Force, NEV, and Telecom Infra project? can you follow up?

KLAS done and updated logo in web, for Girls force, KLIM, NEV, but waiting for the confirm logo :), TIP it still processing
