### ISSUE TITLE
Logo Kubernetes Community Days Indonesia 2021

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#5]
### Acceptance Criteria
- [x] Adding Indonesia 2021 in the main logo https://www.cncf.io/blog/2019/10/03/announcing-kubernetes-community-days/

### Due Date
29 July 2021

### Output
Logo file

**Comment by assyafii** [comment]
Logo v1 done, at https://drive.google.com/drive/u/1/folders/1gABEYQOhjniYZVsWUEnUCAhYkK_IBogl
