### ISSUE TITLE
create 3 zoom calls for dryrun

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#62]
- [x] email speakers
- [x] email organizers
- [x] email sponsored talks
- [x] email MC
- [x] email volunteer
- [x] email panelist
- [x] email moderator

**Comment by ariscahyadi** [comment]
@zufardhiyaulhaq we need to add “booth speaker” for the dry-run.
- [x] Microsoft (22/11/2021)
- [x] AWS (22/11/2021)
- [ ] NetApp (23/11/2021)
- [ ] Nutanix (23/11/2021)
- [ ] Google (TBD)
