### ISSUE TITLE
Sponsorship Prospectus content

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#7]
### Acceptance Criteria
- [x] Sponsor Tier
- [x] Sponsorship process
- [x] Call for Sponsorship opening date
- [x] Call for Sponsorship closing date
- [x] make Other Marketing Opportunities only for lucky attendees

Optional:
- [ ] Virtual Event Venue

### Due Date
5 August 2021

### Output
markdown file

**Comment by zufardhiyaulhaq** [comment]
@cloudnative-id/kubernetes-community-days share with you the Sponsorship Prospectus document. please help to review. https://docs.google.com/document/d/1z0A3DTdIc37Ac-a5jDipVvoQq69zkSy0Mn6h-bY5-W4/

**Comment by zufardhiyaulhaq** [comment]
@goFrendiAsgard @bachrilq @whippedcreamm please check the list if the content is already fixed.

**Comment by goFrendiAsgard** [comment]
Thanks for the great work, @zufardhiyaulhaq.
Do we need to put our email address as well or just you, @whippedcreamm, and @assyafii?

As for the theme, I think we can discuss more about it in our next meeting.

**Comment by whippedcreamm** [comment]
Some updates for [Sponsorship Prospectus Documents.](https://docs.google.com/document/d/1z0A3DTdIc37Ac-a5jDipVvoQq69zkSy0Mn6h-bY5-W4/edit?usp=sharing)
- Add one paragram to About KCD
- Delete event Theme KCD Indonesia 2021 overview
- Set date&venue
- Add topics
- Fix sponsorship tier
- Add other marketing opportunities
- Input important dates
- Fix sponsorship process
- Fix contact info

Presentation version can be accessed [here](https://docs.google.com/presentation/d/1Jv9nHRwtH03MKPcg0120Vas7HC6xKxeeVs0Wo-BesXg/edit?usp=sharing)

**Comment by zufardhiyaulhaq** [comment]
Thanks for your hard work pak @goFrendiAsgard mba @whippedcreamm.
